version: "3.8"
services:
  app:
    build: .
    image: cloud-ide-server:local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public:ro
      # mount docker socket so backend can spawn containers on the host
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
